### ISSUE TITLE
Update to 1.20.1?

### ISSUE THREAD

**Issue by asodugf12** [aesefficio/DynamicVillageMod#15]

**Comment by JoshHawley** [comment]
yes please!

**Comment by Boggyghost** [comment]
This would be amazing if you could!!!

**Comment by kienerxyzzy** [comment]
1.20.1 pls

**Comment by a0a7** [comment]
Thanks to @ben001109 a 1.20.1 version is now available! Up on [Modrinth](https://modrinth.com/mod/dynamic-village/version/0.4) and [Curseforge](https://www.curseforge.com/minecraft/mc-mods/dynamic-village/files/5565479) :)
