### ISSUE TITLE
Source missing?

### ISSUE THREAD

**Issue by foobazbar123** [aesefficio/DynamicVillageMod#16]
Is it my imagination, or is the source in the repository mostly missing or at best incomplete?

**Comment by foobazbar123** [comment]
It doesn't appear to be, to me. The main java file is only 90 lines and appears to be boiler plate/example code. The src/main/resources directory appears to be missing files shown to have been merged in previously. Does this make sense? :)

**Comment by syslev** [comment]
Yea that all makes sense, but that's just the quality of the codebase being shit. This mod doesn't do a lot. 

I checked against my local clone and the remote 1.19.2 branch is up to date. Building should work.

**Comment by a0a7** [comment]
Yeah it's all good
